import os
import pandas as pd
import sys

# --- Configuration ---
# The full CSV file you downloaded (with 1M+ rows)
FULL_CSV_PATH = 'data/raw/Cap3D_automated_Objaverse_full.csv'

# The file generated by script 01
UID_LIST_PATH = 'data/available_uids.txt'

# The final, clean metadata file for your 10k subset
OUTPUT_CSV_PATH = 'data/processed/metadata_10k.csv'

# The number of samples you want in your subset
SUBSET_SIZE = 10000
# --- End Configuration ---

def create_subset():
    """
    1. Loads the list of available UIDs.
    2. Loads the full captions CSV.
    3. Filters the CSV to only include available UIDs.
    4. Takes a subset of SUBSET_SIZE.
    5. Saves the new, clean metadata CSV.
    """
    
    # --- Step 1: Load Available UIDs ---
    print(f"Loading available UIDs from {UID_LIST_PATH}...")
    try:
        with open(UID_LIST_PATH, 'r') as f:
            # Use a set for much faster lookups
            available_uids = set(line.strip() for line in f)
        
        if not available_uids:
            print(f"Error: {UID_LIST_PATH} is empty.", file=sys.stderr)
            sys.exit(1)
            
        print(f"Loaded {len(available_uids)} available UIDs.")
    except FileNotFoundError:
        print(f"Error: File not found: {UID_LIST_PATH}", file=sys.stderr)
        print("Please run 'scripts/01_get_available_uids.py' first.", file=sys.stderr)
        sys.exit(1)

    # --- Step 2: Load Full Captions CSV ---
    print(f"Loading full captions CSV from {FULL_CSV_PATH}...")
    try:
        # Use pandas to correctly load the CSV, specifying no header
        # and providing our own column names.
        df_full = pd.read_csv(
            FULL_CSV_PATH,
            header=None,
            names=['uid', 'caption']
        )
        print(f"Loaded {len(df_full)} total captions.")
    except FileNotFoundError:
        print(f"Error: File not found: {FULL_CSV_PATH}", file=sys.stderr)
        print("Please download 'Cap3D_automated_Objaverse_full.csv' to 'data/raw/'.", file=sys.stderr)
        sys.exit(1)

    # --- Step 3: Filter DataFrame ---
    print("Filtering DataFrame to match available UIDs...")
    
    # This is the "filter-first" step. We keep only rows
    # where the 'uid' is in our set of available UIDs.
    df_available = df_full[df_full['uid'].isin(available_uids)]
    
    available_count = len(df_available)
    print(f"Found {available_count} matching assets with both captions and renders.")

    if available_count == 0:
        print("Error: No matching UIDs found. Check your paths and file contents.", file=sys.stderr)
        sys.exit(1)

    # --- Step 4: Create Subset ---
    if available_count < SUBSET_SIZE:
        print(f"Warning: Found only {available_count} assets, which is less than the desired {SUBSET_SIZE}.", file=sys.stderr)
        print("Using all available assets.")
        df_subset = df_available
    else:
        # Take the first SUBSET_SIZE rows
        df_subset = df_available.iloc[:SUBSET_SIZE]
        print(f"Created subset with {len(df_subset)} assets.")

    # --- Step 5: Save Final CSV ---
    # Ensure the output directory (data/processed/) exists
    os.makedirs(os.path.dirname(OUTPUT_CSV_PATH), exist_ok=True)
    
    # Save the final, clean CSV.
    # index=False prevents pandas from adding an extra 'Unnamed: 0' column
    df_subset.to_csv(OUTPUT_CSV_PATH, index=False)
    
    print(f"Successfully saved {len(df_subset)} samples to {OUTPUT_CSV_PATH}")
    print("\n--- Sample of the final data ---")
    print(df_subset.head())
    print("----------------------------------")

if __name__ == '__main__':
    create_subset()